#ifndef IMAGEVIEWER_APP_RESOURCE_ID_H_
#define IMAGEVIEWER_APP_RESOURCE_ID_H_

#include "wx/defs.h"

enum {
  // menu id in main frame
  ID_MENU_INFO_ABOUT = wxID_HIGHEST + 1,
  ID_MENU_BACKGROUND_COLOUR,
  ID_MENU_SELECT_DIRECTORY,
  ID_MENU_IMPORT,

  // thread id
  ID_LOAD_IMAGE_THREAD,

  ID_ROTATE_CLOCK_WISE,
  ID_ROTATE_COUNTER_CLOCK_WISE,
  ID_CONVERT_TO_MONO
};
#endif  // IMAGEVIEWER_APP_RESOURCE_ID_H_
